import { PALETA } from '@/theme/palette';
import { ELEVACION } from '@/theme/theme';

/** Hoja de estilos del asistente: vive aparte para que la página quede en lo que hace, no en cómo se ve. */
export const estilos: Record<string, React.CSSProperties> = {
  shell: { height: 'calc(100vh - 56px)', display: 'flex', overflow: 'hidden' },

  // ── Hilo ──────────────────────────────────────────────────────────────────
  centro: { flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column' },
  barraCaso: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 24px',
    borderBottom: `1px solid ${PALETA.borde}`,
    background: PALETA.moradoBg,
  },
  casoTitulo: { fontSize: 13, fontWeight: 600, color: PALETA.texto },
  casoPartes: { fontSize: 11.5, color: PALETA.textoSuave },
  hilo: { flex: 1, overflowY: 'auto', padding: '28px 24px 8px' },
  columnaLectura: { maxWidth: 680, margin: '0 auto' },
  turnoAsistente: {
    fontSize: 15,
    lineHeight: 1.7,
    color: PALETA.texto,
    whiteSpace: 'pre-wrap',
    margin: '0 0 26px',
  },
  turnoInspector: {
    fontSize: 14.5,
    lineHeight: 1.6,
    color: PALETA.texto,
    whiteSpace: 'pre-wrap',
    background: 'rgba(0,0,0,0.03)',
    borderLeft: `2px solid ${PALETA.borde}`,
    borderRadius: '0 8px 8px 0',
    padding: '10px 14px',
    margin: '0 0 22px',
  },
  vacio: { paddingTop: 40, display: 'flex', flexDirection: 'column', gap: 12, alignItems: 'flex-start' },
  vacioTitulo: { margin: 0, fontSize: 24, color: PALETA.texto, fontWeight: 500 },
  vacioTexto: { margin: 0, fontSize: 14.5, lineHeight: 1.65, color: PALETA.textoSuave, maxWidth: 520 },
  chips: { display: 'flex', flexWrap: 'wrap', gap: 8, marginTop: 6 },
  chip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 7,
    padding: '7px 12px',
    border: `1px solid ${PALETA.borde}`,
    borderRadius: 999,
    background: 'transparent',
    color: PALETA.texto,
    fontSize: 13,
    fontFamily: 'inherit',
    cursor: 'pointer',
  },

  // ── Compositor ────────────────────────────────────────────────────────────
  compositorWrap: { padding: '0 24px 18px', position: 'relative' },
  compositor: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: 8,
    padding: '8px 10px',
    border: `1px solid ${PALETA.borde}`,
    borderRadius: 14,
    background: PALETA.superficie,
    boxShadow: ELEVACION.base,
  },
  textarea: {
    flex: 1,
    border: 'none',
    outline: 'none',
    resize: 'none',
    background: 'transparent',
    fontFamily: 'inherit',
    fontSize: 14.5,
    lineHeight: 1.6,
    color: PALETA.texto,
    padding: '7px 2px',
    maxHeight: 320,
  },
  enviarBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 7,
    padding: '8px 14px',
    borderRadius: 10,
    border: 'none',
    fontSize: 13.5,
    fontFamily: 'inherit',
    flexShrink: 0,
  },
  enviarActivo: { background: PALETA.morado, color: '#fff', cursor: 'pointer' },
  enviarInactivo: { background: 'rgba(0,0,0,0.05)', color: PALETA.textoTenue, cursor: 'not-allowed' },
  pieCompositor: { margin: '8px 2px 0', fontSize: 11.5, color: PALETA.textoTenue },
  iconBtn: {
    border: 'none',
    background: 'transparent',
    color: PALETA.textoSuave,
    cursor: 'pointer',
    padding: 5,
    display: 'inline-flex',
    alignItems: 'center',
  },
  menu: {
    border: `1px solid ${PALETA.borde}`,
    borderRadius: 12,
    background: PALETA.superficie,
    boxShadow: ELEVACION.media,
    padding: 6,
    marginBottom: 8,
    maxHeight: 300,
    overflowY: 'auto',
  },
  menuItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    width: '100%',
    textAlign: 'left',
    border: 'none',
    background: 'transparent',
    borderRadius: 8,
    padding: '8px 10px',
    cursor: 'pointer',
    fontFamily: 'inherit',
    color: PALETA.texto,
  },
  menuItemActivo: { background: PALETA.moradoBg },
  menuClave: { display: 'block', fontSize: 13.5, fontWeight: 600 },
  menuDesc: { display: 'block', fontSize: 12, color: PALETA.textoSuave },
  skillActiva: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '5px 6px 5px 11px',
    border: `1px solid ${PALETA.borde}`,
    borderRadius: 999,
    marginBottom: 8,
    fontSize: 12.5,
    color: PALETA.texto,
  },
  skillClave: { fontWeight: 600, color: PALETA.moradoOscuro },
  skillDesc: { color: PALETA.textoSuave },
  adjuntos: { display: 'flex', flexWrap: 'wrap', gap: 6, marginBottom: 8 },
  adjunto: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 4,
    padding: '4px 6px 4px 10px',
    border: `1px solid ${PALETA.borde}`,
    borderRadius: 8,
    fontSize: 12,
    color: PALETA.texto,
  },
  textoTenue: { color: PALETA.textoTenue, fontSize: 13 },
};
